import os

base = os.path.join(os.getcwd(), 'src', 'app', 'dashboard', 'deals', '[id]')

# Write the client file with real unicode chars (not escape sequences)
lines = [
    "'use client'\n",
    "\n",
    "import { useState, useTransition } from 'react'\n",
    "import { useRouter } from 'next/navigation'\n",
    "import { DEAL_STATUSES, type DealStatus, SUPPLIERS, PLATFORMS } from '@/lib/deals/constants'\n",
    "import { updateDealStatus } from '@/lib/deals/actions'\n",
    "import EditDealModal from '../EditDealModal'\n",
    "\n",
    "const STATUS_ORDER: DealStatus[] = [\n",
    "  'AUCTION_WON','AWAITING_PAYMENT_LINK','PAYMENT_REQUIRED','PAID',\n",
    "  'READY_FOR_PICKUP','IN_TRANSIT_USA','AT_SB_TECHNOLOGY','IN_TRANSIT_DUBAI',\n",
    "  'AT_TURBO_LOGISTICS','RECEIVED_BY_MOBITECH','PARTIALLY_SOLD','SOLD','DEAL_CLOSED',\n",
    "]\n",
    "\n",
    "function fmt(n: number) { return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',minimumFractionDigits:2}).format(n||0) }\n",
    "function fmtS(n: number) { return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n||0) }\n",
    "function fmtDate(d: string|null|undefined) { if(!d) return '\u2014'; return new Date(d).toLocaleDateString('en-AE',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}) }\n",
    "function fmtD(d: string|null|undefined) { if(!d) return '\u2014'; return new Date(d).toLocaleDateString('en-AE',{day:'2-digit',month:'short',year:'numeric'}) }\n",
    "function daysSince(d: string) { return Math.floor((Date.now()-new Date(d).getTime())/86400000) }\n",
    "\n",
    "interface Props { deal: any }\n",
    "\n",
    "export default function DealDetailClient({ deal }: Props) {\n",
    "  const router = useRouter()\n",
    "  const [isPending,startTransition] = useTransition()\n",
    "  const [showEdit,setShowEdit] = useState(false)\n",
    "  const [showAdvance,setShowAdvance] = useState(false)\n",
    "  const [advanceNote,setAdvanceNote] = useState('')\n",
    "  const [error,setError] = useState('')\n",
    "\n",
    "  const currentStep = STATUS_ORDER.indexOf(deal.status as DealStatus)\n",
    "  const nextStatus  = currentStep < STATUS_ORDER.length-1 ? STATUS_ORDER[currentStep+1] : null\n",
    "  const isClosed    = deal.status === 'DEAL_CLOSED'\n",
    "  const days        = daysSince(deal.auction_won_date)\n",
    "  const overdue     = !isClosed && days >= 30\n",
    "\n",
    "  const statusHistory = [...(deal.deal_status_history||[])].sort((a:any,b:any)=>new Date(b.changed_at).getTime()-new Date(a.changed_at).getTime())\n",
    "  const editHistory   = [...(deal.deal_edit_history||[])].sort((a:any,b:any)=>new Date(b.edited_at).getTime()-new Date(a.edited_at).getTime())\n",
    "\n",
    "  const handleAdvance = () => {\n",
    "    if(!nextStatus) return\n",
    "    setError('')\n",
    "    startTransition(async () => {\n",
    "      const result = await updateDealStatus(deal.id, nextStatus, advanceNote||undefined)\n",
    "      if(result.error) { setError(result.error) }\n",
    "      else { setShowAdvance(false); setAdvanceNote(''); router.refresh() }\n",
    "    })\n",
    "  }\n",
    "\n",
    "  const st = (s: string) => DEAL_STATUSES[s as DealStatus]\n",
    "\n",
    "  return (\n",
    "    <div className=\"page-root\">\n",
    "\n",
    "      {/* Header */}\n",
    "      <div className=\"deal-detail-header\">\n",
    "        <div className=\"dh-left\">\n",
    "          <a href=\"/dashboard/deals\" className=\"dh-back\">\u2190 Back to Deals</a>\n",
    "          <div className=\"dh-title-row\">\n",
    "            <h1 className=\"dh-title\">{deal.deal_number}</h1>\n",
    "            <span className={`status-badge ${st(deal.status)?.color||''}`}>{st(deal.status)?.label}</span>\n",
    "            {overdue && <span className=\"overdue-badge\">[!] {days}d overdue</span>}\n",
    "          </div>\n",
    "          <p className=\"dh-sub\">{deal.model} \u00b7 {[deal.storage,deal.grade,deal.carrier,deal.color].filter(Boolean).join(' \u00b7 ')}</p>\n",
    "        </div>\n",
    "        <div className=\"dh-actions\">\n",
    "          <button className=\"btn-ghost\" onClick={()=>setShowEdit(true)}>[Edit] Edit Deal</button>\n",
    "          {nextStatus && !isClosed && (\n",
    "            <button className=\"btn-advance\" onClick={()=>setShowAdvance(true)}>\n",
    "              \u2192 {st(nextStatus)?.label}\n",
    "            </button>\n",
    "          )}\n",
    "        </div>\n",
    "      </div>\n",
    "\n",
    "      {/* Pipeline */}\n",
    "      <div className=\"pipeline-wrap\">\n",
    "        <div className=\"pipeline-scroll\">\n",
    "          {STATUS_ORDER.map((status,idx) => {\n",
    "            const isDone=idx<currentStep, isCur=idx===currentStep\n",
    "            const meta=st(status)\n",
    "            return (\n",
    "              <div key={status} className={`pipeline-step ${isDone?'step-done':isCur?'step-current':'step-future'}`}>\n",
    "                <div className=\"step-circle\">{isDone?'\u2713':<span className=\"step-num\">{idx+1}</span>}</div>\n",
    "                <div className=\"step-label\">{meta?.label}</div>\n",
    "                {idx<STATUS_ORDER.length-1 && <div className={`step-connector ${isDone?'connector-done':'connector-future'}`}/>}\n",
    "              </div>\n",
    "            )\n",
    "          })}\n",
    "        </div>\n",
    "      </div>\n",
    "\n",
    "      {/* Financial Cards */}\n",
    "      <div className=\"deal-fin-grid\">\n",
    "        <div className=\"fin-card\">\n",
    "          <span className=\"fin-label\">Winning Bid</span>\n",
    "          <span className=\"fin-value\">{fmt(deal.unit_cost)} <span className=\"fin-per\">/ unit</span></span>\n",
    "          <span className=\"fin-sub\">{deal.quantity} units total</span>\n",
    "        </div>\n",
    "        <div className=\"fin-card\">\n",
    "          <span className=\"fin-label\">Bid Total</span>\n",
    "          <span className=\"fin-value\">{fmtS(deal.total_cost)}</span>\n",
    "          <span className=\"fin-sub\">Before fees</span>\n",
    "        </div>\n",
    "        <div className=\"fin-card fin-card-amber\">\n",
    "          <span className=\"fin-label\">Auction Fee</span>\n",
    "          <span className=\"fin-value fin-amber\">{fmt(deal.auction_fee)}</span>\n",
    "          <span className=\"fin-sub\">{deal.total_cost>0?((deal.auction_fee/deal.total_cost)*100).toFixed(1):0}% of bid</span>\n",
    "        </div>\n",
    "        <div className=\"fin-card fin-card-highlight\">\n",
    "          <span className=\"fin-label\">Total Commitment</span>\n",
    "          <span className=\"fin-value fin-white\">{fmtS(deal.total_commitment)}</span>\n",
    "          <span className=\"fin-sub\">Bid + all fees</span>\n",
    "        </div>\n",
    "        <div className=\"fin-card fin-card-blue\">\n",
    "          <span className=\"fin-label\">Funding Source</span>\n",
    "          <span className=\"fin-value fin-blue\">{deal.funding_source==='AMEX'?'[AMEX] Amex':deal.funding_source==='CASH_POOL'?'[Cash] Cash':'[Mixed]'}</span>\n",
    "          <span className=\"fin-sub\">{deal.funding_source==='AMEX'?fmtS(deal.amex_amount)+' on card':deal.funding_source==='CASH_POOL'?fmtS(deal.cash_amount)+' from pool':'Amex '+fmtS(deal.amex_amount)+' / Cash '+fmtS(deal.cash_amount)}</span>\n",
    "        </div>\n",
    "        <div className={`fin-card ${deal.cashback_eligible?'fin-card-green':''}`}>\n",
    "          <span className=\"fin-label\">Amex Cashback (2%)</span>\n",
    "          <span className={`fin-value ${deal.cashback_eligible?'fin-green':'fin-muted'}`}>{deal.cashback_eligible?'+ '+fmt(deal.total_commitment*0.02):'Not eligible'}</span>\n",
    "          <span className=\"fin-sub\">{deal.amex_statement_date?'Statement: '+fmtD(deal.amex_statement_date):'No statement date'}</span>\n",
    "        </div>\n",
    "      </div>\n",
    "\n",
    "      {/* Body Grid */}\n",
    "      <div className=\"deal-body-grid\">\n",
    "        <div className=\"deal-info-panel\">\n",
    "          <div className=\"panel-title\">[Notes] Deal Information</div>\n",
    "          <div className=\"info-group\">\n",
    "            <div className=\"info-section-label\">Product</div>\n",
    "            <div className=\"info-row\"><span>Model</span><strong>{deal.model}</strong></div>\n",
    "            <div className=\"info-row\"><span>Storage</span><strong>{deal.storage||'\u2014'}</strong></div>\n",
    "            <div className=\"info-row\"><span>Grade</span><strong>{deal.grade||'\u2014'}</strong></div>\n",
    "            <div className=\"info-row\"><span>Carrier</span><strong>{deal.carrier||'\u2014'}</strong></div>\n",
    "            <div className=\"info-row\"><span>Color</span><strong>{deal.color||'\u2014'}</strong></div>\n",
    "            <div className=\"info-row\"><span>Quantity</span><strong>{deal.quantity} units</strong></div>\n",
    "          </div>\n",
    "          <div className=\"info-group\">\n",
    "            <div className=\"info-section-label\">Supplier</div>\n",
    "            <div className=\"info-row\"><span>Supplier</span><strong>{SUPPLIERS.find((s:any)=>s.value===deal.supplier)?.label||deal.supplier}</strong></div>\n",
    "            <div className=\"info-row\"><span>Platform</span><strong>{PLATFORMS.find((p:any)=>p.value===deal.auction_platform)?.label||deal.auction_platform}</strong></div>\n",
    "          </div>\n",
    "          <div className=\"info-group\">\n",
    "            <div className=\"info-section-label\">Key Dates</div>\n",
    "            <div className=\"info-row\"><span>Auction Won</span><strong>{fmtD(deal.auction_won_date)}</strong></div>\n",
    "            <div className=\"info-row\"><span>Payment Date</span><strong>{fmtD(deal.payment_date)}</strong></div>\n",
    "            <div className=\"info-row\"><span>Shipped USA</span><strong>{fmtD(deal.shipped_usa_date)}</strong></div>\n",
    "            <div className=\"info-row\"><span>Arrived Dubai</span><strong>{fmtD(deal.arrived_dubai_date)}</strong></div>\n",
    "            <div className=\"info-row\"><span>Received (Mobitech)</span><strong>{fmtD(deal.received_mobitech_date)}</strong></div>\n",
    "            <div className=\"info-row\"><span>Deal Closed</span><strong>{fmtD(deal.deal_closed_date)}</strong></div>\n",
    "          </div>\n",
    "          {deal.notes && (<div className=\"info-group\"><div className=\"info-section-label\">Notes</div><p className=\"info-notes\">{deal.notes}</p></div>)}\n",
    "          <div className=\"info-group\">\n",
    "            <div className=\"info-section-label\">Profit (Deal Level)</div>\n",
    "            <div className=\"info-row\"><span>Total Revenue</span><strong className=\"fin-green\">{fmtS(deal.total_revenue)}</strong></div>\n",
    "            <div className=\"info-row\"><span>COGS</span><strong>{fmtS(deal.total_cogs)}</strong></div>\n",
    "            <div className=\"info-row\"><span>Gross Profit</span><strong className={deal.gross_profit>0?'fin-green':deal.gross_profit<0?'fin-red':''}>{fmtS(deal.gross_profit)}</strong></div>\n",
    "          </div>\n",
    "        </div>\n",
    "\n",
    "        <div className=\"deal-history-panel\">\n",
    "          <div className=\"panel-title\">[History] Status History</div>\n",
    "          {statusHistory.length===0 ? (<p className=\"history-empty\">No status changes yet.</p>) : (\n",
    "            <div className=\"status-history-list\">\n",
    "              {statusHistory.map((h:any)=>(\n",
    "                <div key={h.id} className=\"sh-item\">\n",
    "                  <div className=\"sh-dot\"/>\n",
    "                  <div className=\"sh-body\">\n",
    "                    <div className=\"sh-top\">\n",
    "                      {h.old_status && (<><span className={`status-badge ${st(h.old_status)?.color||''}`} style={{fontSize:'10px'}}>{st(h.old_status)?.label}</span><span className=\"sh-arrow\">\u2192</span></>)}\n",
    "                      <span className={`status-badge ${st(h.new_status)?.color||''}`} style={{fontSize:'10px'}}>{st(h.new_status)?.label}</span>\n",
    "                    </div>\n",
    "                    {h.notes && <p className=\"sh-note\">\"{h.notes}\"</p>}\n",
    "                    <span className=\"sh-when\">{fmtDate(h.changed_at)}</span>\n",
    "                  </div>\n",
    "                </div>\n",
    "              ))}\n",
    "            </div>\n",
    "          )}\n",
    "\n",
    "          <div className=\"panel-title\" style={{marginTop:'24px'}}>[Edit] Edit History</div>\n",
    "          {editHistory.length===0 ? (<p className=\"history-empty\">No edits made yet.</p>) : (\n",
    "            <div className=\"edit-history\">\n",
    "              {editHistory.map((e:any)=>(\n",
    "                <div key={e.id} className=\"edit-history-item\">\n",
    "                  <div className=\"edit-history-header\">\n",
    "                    <span className=\"edit-history-who\">Edited</span>\n",
    "                    <span className=\"edit-history-when\">{fmtDate(e.edited_at)}</span>\n",
    "                  </div>\n",
    "                  {e.edit_note && <p className=\"edit-history-reason\">\"{e.edit_note}\"</p>}\n",
    "                  <div className=\"edit-field-changes\">\n",
    "                    {(e.field_changes as any[]).map((fc:any,i:number)=>(\n",
    "                      <div key={i} className=\"edit-field-change\">\n",
    "                        <span className=\"efc-label\">{fc.label}</span>\n",
    "                        <span className=\"efc-old\">{fc.old_value||'\u2014'}</span>\n",
    "                        <span className=\"efc-arrow\">\u2192</span>\n",
    "                        <span className=\"efc-new\">{fc.new_value||'\u2014'}</span>\n",
    "                      </div>\n",
    "                    ))}\n",
    "                  </div>\n",
    "                </div>\n",
    "              ))}\n",
    "            </div>\n",
    "          )}\n",
    "        </div>\n",
    "      </div>\n",
    "\n",
    "      {/* Advance Modal */}\n",
    "      {showAdvance && nextStatus && (\n",
    "        <div className=\"modal-overlay\" onClick={(e:any)=>{if(e.target===e.currentTarget)setShowAdvance(false)}}>\n",
    "          <div className=\"modal-box\" style={{maxWidth:'480px'}}>\n",
    "            <div className=\"modal-header\">\n",
    "              <div><h2 className=\"modal-title\">Advance Deal Status</h2><p className=\"modal-sub\">{deal.deal_number}</p></div>\n",
    "              <button className=\"modal-close\" onClick={()=>setShowAdvance(false)}>\u00d7</button>\n",
    "            </div>\n",
    "            <div className=\"modal-form\">\n",
    "              <div className=\"advance-status-preview\">\n",
    "                <div className=\"asp-from\">\n",
    "                  <span className=\"asp-label\">Current</span>\n",
    "                  <span className={`status-badge ${st(deal.status)?.color||''}`}>{st(deal.status)?.label}</span>\n",
    "                </div>\n",
    "                <span className=\"asp-arrow\">\u2192</span>\n",
    "                <div className=\"asp-to\">\n",
    "                  <span className=\"asp-label\">New Status</span>\n",
    "                  <span className={`status-badge ${st(nextStatus)?.color||''}`}>{st(nextStatus)?.label}</span>\n",
    "                </div>\n",
    "              </div>\n",
    "              <div className=\"form-group\">\n",
    "                <label className=\"form-label\">Note <span className=\"form-hint-inline\">(optional)</span></label>\n",
    "                <input type=\"text\" className=\"form-input\" placeholder=\"e.g. Payment confirmed by SB team\" value={advanceNote} onChange={(e:any)=>setAdvanceNote(e.target.value)} onKeyDown={(e:any)=>{if(e.key==='Enter')handleAdvance()}} autoFocus/>\n",
    "              </div>\n",
    "              {error && <div className=\"login-error\">\u26a0\ufe0f {error}</div>}\n",
    "              <div className=\"modal-actions\">\n",
    "                <button className=\"btn-ghost\" onClick={()=>setShowAdvance(false)}>Cancel</button>\n",
    "                <button className=\"btn-advance\" disabled={isPending} onClick={handleAdvance} id=\"confirm-advance-btn\">\n",
    "                  {isPending?'Updating...':`\u2713 Confirm: ${st(nextStatus)?.label}`}\n",
    "                </button>\n",
    "              </div>\n",
    "            </div>\n",
    "          </div>\n",
    "        </div>\n",
    "      )}\n",
    "\n",
    "      {showEdit && <EditDealModal deal={deal} onClose={()=>{setShowEdit(false);router.refresh()}}/> }\n",
    "    </div>\n",
    "  )\n",
    "}\n",
]

out_path = os.path.join(base, 'DealDetailClient.tsx')
with open(out_path, 'w', encoding='utf-8', newline='\n') as f:
    f.writelines(lines)

print(f'Written: {os.path.getsize(out_path)} bytes')
print('Done!')
