-- 010_admin_roles.sql

CREATE TYPE app_role AS ENUM ('SUPER_ADMIN', 'SALES', 'LOGISTICS', 'FINANCE');

CREATE TABLE IF NOT EXISTS user_roles (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  email       TEXT NOT NULL,
  role        app_role NOT NULL DEFAULT 'SALES',
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(user_id)
);

-- Function to auto-update updated_at
CREATE TRIGGER user_roles_updated_at BEFORE UPDATE ON user_roles FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- Add target_price to inventory so Super Admin can set the goal price for Sales team
ALTER TABLE inventory_items ADD COLUMN IF NOT EXISTS target_price NUMERIC(12,2) DEFAULT 0;

-- Sales invoices statuses (New ones generated by Sales will be PENDING_APPROVAL)
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS approval_status TEXT NOT NULL DEFAULT 'APPROVED';
